import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="lemonade" className="bg-amber-50">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="h-[10vh] navbar  bg-amber-100 flex justify-between">
          <Link href={'/'}>Logo</Link>
          
          <div className="w-1/5 flex justify-around">
            <button>Language</button>
            <button>Login</button>
            </div>
           </nav>
        {children}
      </body>
    </html>
  );
}
