import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { House, Languages, LogIn } from "lucide-react";
import LanguageToggle from "./Components/LanguageToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className=" navbar  absolute bg-transparent  backdrop-blur-sm z-50   flex justify-between ">
          <Link
            className="ml-5 p-1 rounded-lg text-[#E7A24A]  hover:text-amber-50   hover:scale-105 hover:bg-[#E7A24A] transition-all duration-200   flex items-center justify-center"
            href={"/"}>
            <House size={35} />
          </Link>
          <div className="w-[10%] flex justify-around">
            <LanguageToggle />
            <button className=" text-[#E7A24A]   hover:scale-120 hover:text-amber-50 transition-all duration-200   flex items-center justify-center">
              <LogIn size={35} />
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
