import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { House, LogIn } from "lucide-react";
import LanguageToggle from "./Components/LanguageToggle";

import { Roboto, Tajawal } from "next/font/google";

const primaryFont = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

const arabicFont = Tajawal({
  weight: ["400", "700"],
  subsets: ["arabic"],
  variable: "--font-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${primaryFont.variable} ${arabicFont.variable} antialiased`}>
        <nav className="     navbar  fixed bg-transparent  backdrop-blur-sm z-50   flex justify-between ">
          <Link
            className="ml-5 p-1 rounded-lg text-[#E7A24A]  hover:text-amber-50   hover:scale-105 hover:bg-[#E7A24A] transition-all duration-200   flex items-center justify-center"
            href={"/"}>
            <House size={35} />
          </Link>
          <div className="w-[10%] flex justify-around">
            <LanguageToggle />
            <button className=" text-[#E7A24A]   hover:scale-120 hover:text-amber-50 transition-all duration-200   flex items-center justify-center">
              <LogIn size={35} />
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
